# Generated by Django 6.0 on 2026-03-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_resettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
