# Generated by Django 6.0 on 2026-03-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_review_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
